keyVault:
  enabled: true
  tenantId: "72fca1b1-2c2e-4376-a445-294d80196804"
  kvName: "aapp-t-kv-kt3dmhwuxuelw"
  secrets:
    - name: postgres-administrator-password
    - name: web-password
    - name: app-token
    - name: aes-secret
  servicePrincipalSecretName: azurekeyvaultsecretsprovider-aapp-t-aks  # secret name of SP
  provider: azure                          # choose your provider
  #volumeName: kvsecrets                    # [Optional] volume name defaults to kvsecrets 
  #spcName: secret-privider-class           # [Optional] name of secret-privider-class operator defaults to .Release.Name "secret-privider-class"
  #secretsDir: /secrets                     # [Optional] path where secrets will be mounted defaults to /secrets